language: node_js
node_js:
    - "0.10"
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - npm i -g jasmine-node gulp knex
script: 
    - npm install
    - gulp travis_migrate travis_seed test