language: node_js
node_js:
    - "0.10"
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - npm i -g jasmine-node gulp
    - gulp travis_migrate
script: 
    - gulp travis_seed
    - jasmine-node spec/travisSpec.js